# Generated by Django 5.0.6 on 2024-05-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('eng_transl', models.CharField(max_length=100)),
                ('kab_transl', models.CharField(max_length=100)),
                ('ipa', models.CharField(max_length=100)),
                ('audio_url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('audio_url', models.URLField(max_length=300)),
                ('text', models.TextField()),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabardian_poetry_api.vocabulary')),
            ],
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='words',
            field=models.ManyToManyField(related_name='vocabulary_words', to='kabardian_poetry_api.word'),
        ),
    ]
