# Generated by Django 5.0.6 on 2024-05-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabardian_poetry_api', '0002_remove_word_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='audio_url',
        ),
    ]
