# Generated by Django 5.0.6 on 2024-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabardian_poetry_api', '0003_remove_poem_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='type',
            field=models.CharField(default='noun', max_length=100),
        ),
    ]
