# Generated by Django 5.0.6 on 2024-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabardian_poetry_api', '0004_word_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='type',
            field=models.CharField(default='nouns', max_length=100),
        ),
    ]
