# Generated by Django 5.0.6 on 2024-05-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabardian_poetry_api', '0006_rename_kab_transl_word_rus_transl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabardian_poetry_api.word'),
        ),
    ]
