# Generated by Django 5.0.6 on 2024-05-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabardian_poetry_api', '0007_alter_poem_vocabulary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vocabulary',
        ),
    ]
