# Generated by Django 5.0.6 on 2024-05-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabardian_poetry_api', '0008_delete_vocabulary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='vocabulary',
            new_name='words',
        ),
    ]
