# Generated by Django 5.0.6 on 2024-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabardian_poetry_api', '0010_remove_poem_words_poem_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='poem',
            name='words',
            field=models.ManyToManyField(to='kabardian_poetry_api.word'),
        ),
    ]
