# Generated by Django 5.0.6 on 2024-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_remove_word_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='text',
            new_name='contents',
        ),
    ]
