# Generated by Django 5.0.6 on 2024-07-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_rename_text_poem_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='contents',
            new_name='text',
        ),
    ]
