# Generated by Django 5.0.6 on 2024-07-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_rename_contents_poem_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='text',
            new_name='contents',
        ),
    ]
