# Generated by Django 5.0.6 on 2024-07-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_alter_poem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='user',
        ),
    ]
