# Generated by Django 5.0.6 on 2024-07-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0013_poem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='owner',
        ),
    ]
